### ISSUE TITLE
Bug Report: Refresh timer failed

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/GetMyIP#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues (both open and closed).

### What happened or didn't happen?

Error message in application log file. (see below)

Appears to be a threading issue attempting to show a snackbar message.

### Steps To Reproduce

Run Get My IP with automatic refresh enabled.

Error happens infrequently.  Error isn't reproducible on demand. 

### Version

0.12.2

### Windows Version

Windows 11 24H2 build 26100.2454

### Relevant log output

```shell
2024/12/01 16:16:58.73 ERROR  Refresh timer failed
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|7_0()
   at System.Windows.Application.get_MainWindow()
   at GetMyIP.Dialogs.SnackBarMsg.ClearAndQueueMessage(String message) in V:\Source\Repos\GetMyIP\GetMyIP\Dialogs\SnackBarMsg.cs:line 17
   at GetMyIP.ViewModels.NavigationViewModel.RefreshExternalAsync() in V:\Source\Repos\GetMyIP\GetMyIP\ViewModels\NavigationViewModel.cs:line 273
   at GetMyIP.Helpers.RefreshHelpers.TimerElapsed(Object sender, ElapsedEventArgs e) in V:\Source\Repos\GetMyIP\GetMyIP\Helpers\RefreshHelpers.cs:line 54
```

**Comment by Timthreetwelve** [comment]
My internet has been down until a few minutes ago. ☹️ Kind of hard to work on this bug without internet. Not to mention all of the Cyber Monday deals that I missed.

Tim

**Comment by CMTriX** [comment]
Oh no! What deals die you missed? Is the connection back again?

**Comment by Timthreetwelve** [comment]
Connection is back. 🎉

I don't know what deals were missed. Probably better that I don't know anyway. 🤣

**Comment by Timthreetwelve** [comment]
I managed to find the bug.

If automatic refresh is enabled AND the Get My IP window is not minimized, AND the refresh timer executes the refresh, then the error occurs!

The refresh actually happens. The exception came from trying to display the "refreshed" message after the refresh.

Will be fixed in the next release!

Tim

**Comment by CMTriX** [comment]
i have it:

2024/12/03 08:37:41.49 ERROR  Refresh timer failed
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|7_0()
   at System.Windows.Application.get_MainWindow()
   at GetMyIP.Dialogs.SnackBarMsg.ClearAndQueueMessage(String message)
   at GetMyIP.ViewModels.NavigationViewModel.RefreshExternalAsync()
   at GetMyIP.Helpers.RefreshHelpers.TimerElapsed(Object sender, ElapsedEventArgs e)
2024/12/03 08:37:49.50 DEBUG  Opening C:\Users\santa\AppData\Local\Temp\T_K\GetMyIP.20241203.log in default application

**Comment by Timthreetwelve** [comment]
Thanks, that looks like the same exception that I got.

I missed one string in the last release. Would you translate `"Error reading settings file."` and send it in a reply. I'll update the file.

Thanks,
Tim

**Comment by CMTriX** [comment]
Error reading settings file.
Fout bij het lezen van het instellingenbestand.


_Nice word for rummikub: instellingenbestand_

**Comment by CMTriX** [comment]
Click <ins>here</ins> for amazing cybermonday deals!

**Comment by Timthreetwelve** [comment]
Thanks. That link was extremely helpful. 😄
